# Generated by Django 6.0.4 on 2026-04-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaalumno',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='cuentaalumno',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('docente', 'Docente'), ('coordinacion', 'Coordinación académica')], default='alumno', max_length=20),
        ),
    ]
