# Generated by Django 6.0.4 on 2026-04-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cuentaalumno_password_hash_cuentaalumno_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaalumno',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuentaalumno',
            name='reset_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='cuentaalumno',
            name='reset_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentaalumno',
            name='verification_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
