# Generated by Django 5.0 on 2026-05-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cuentaalumno_is_verified_cuentaalumno_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaalumno',
            name='cap_nombre_archivo',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
        migrations.AddField(
            model_name='cuentaalumno',
            name='cap_subido_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuentaalumno',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('docente', 'Docente'), ('coordinacion', 'Coordinación académica'), ('director', 'Dirección / Administración')], default='alumno', max_length=20),
        ),
    ]
