# Generated by Django 5.0 on 2026-05-13 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cap_y_rol_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaalumno',
            name='cap_error_lectura',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cuentaalumno',
            name='cap_texto_extraido',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cuentaalumno',
            name='cap_ultima_lectura_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CapLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=260)),
                ('texto_extraido', models.TextField(blank=True)),
                ('error_lectura', models.CharField(blank=True, max_length=500)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_lecturas', to='core.cuentaalumno')),
            ],
            options={
                'ordering': ['-subido_en'],
            },
        ),
        migrations.CreateModel(
            name='EsquemaEvaluacionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=200)),
                ('periodo', models.CharField(blank=True, max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esquemas_evaluacion', to='core.cuentaalumno')),
            ],
            options={
                'verbose_name': 'Esquema de evaluación',
                'verbose_name_plural': 'Esquemas de evaluación',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='BloqueEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta_grupo', models.CharField(max_length=120)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='core.esquemaevaluacionmateria')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RubroEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_criterio', models.CharField(max_length=400)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('es_fila_total', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='core.bloqueevaluacion')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
