# Generated by Django 5.0 on 2026-05-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evaluacion_cap_lectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='caplectura',
            name='extraccion_resumen',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='cuentaalumno',
            name='cap_extraccion_resumen',
            field=models.CharField(blank=True, help_text='Motor elegido y estadísticas de la última lectura local del CAP.', max_length=240),
        ),
    ]
