# Generated by Django 5.0 on 2026-05-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cap_extraccion_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaalumno',
            name='cap_estructurado',
            field=models.JSONField(blank=True, default=dict, help_text='Parseo estructurado (program_summary, áreas, cursos) desde CAP PDF.'),
        ),
    ]
